package day10Practice;

public class Exception2 {

	public static void main(String[] args) throws ArithmeticException 
	{
		try
		{
			throw new Exception("hello ");
		}
		catch(Exception e)
		{
			
		}
		finally
		{
			
		}
		

	}

}
